FROM python:3.9.1
MAINTAINER Chrissy Aceves "caceves@scripps.edu"
RUN apt-get update -y
WORKDIR .
COPY /outbreak-api-lite .
COPY  /outbreak-api-lite/requirements.txt . 
COPY /outbreak-api-lite/elastic_search.py .
ADD /outbreak-api-lite/elastic_search.py /
RUN /bin/bash -c "pip install -r requirements.txt"
ADD /web/src/localConfig.json .

CMD ["python", "-u", "./elastic_search.py", "-j", "./test_genomics_data.json", "-c", "./localConfig.json"]

