# Dockerfile for running the server side api instance
# base image is python
FROM python 3.9

# set working directory
WORKDIR /outbreak-api-lite

# get the requirements
COPY requirements.txt 
COPY tornado_app.py

# install the pre-recs
RUN pip install -r requirements.txt

# start the api instance
CMD ['python', './tornado_app.py']

