version: '2.2'
services:
  #es from docker image single node
  es:
    container_name: es
    build:
      context: .
      dockerfile: Dockerfile-index
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - some-net
  #ingest the es db
  ingest:
    container_name: ingest
    build:
      context: .
      dockerfile: Dockerfile-es
    restart: on-failure:10
    depends_on:
      - es
    networks:
        - some-net

networks:
  some-net:
    driver: bridge
      
