FROM continuumio/miniconda3
MAINTAINER Chrissy Aceves "caceves@scripps.edu"
ADD /bjorn/envs/env_min.yml .
RUN conda env create -f ./env_min.yml
RUN apt-get -y update && apt-get -y install jq
SHELL ["conda", "run", "-n", "bjorndev", "/bin/bash", "-c"]
COPY /web/src/localConfig.json .
ADD /web/src/localConfig.json .
COPY /bjorn/ .
COPY / .
COPY /bjorn_wrapper.sh .
RUN ls -la /
CMD ["conda", "run", "-n", "bjorndev", "./bjorn_wrapper.sh"] 
