version: '3.9'
services:
  #bjorn run
  bjorn:
    container_name: bjorn
    build:
      context: .
      dockerfile: Dockerfile-bjorn
    profiles: ["new-data"]    
  
  #es from docker image single node
  es:
    container_name: es
    build:
      context: .
      dockerfile: Dockerfile-es
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - some-net
    profiles: ["ingest-data", "website"]
  
  #ingest the es db
  ingest:
    container_name: ingest
    build:
      context: .
      dockerfile: Dockerfile-index
    restart: on-failure:10
    depends_on:
      - es
    networks:
        - some-net
    profiles: ["ingest-data"]
  
  #start up the api
  tornado:
    container_name: tornado
    build:
      context: .
      dockerfile: Dockerfile-server
    restart: on-failure:10
    ports:
      - "8000:8000"
    networks:
      - some-net
    profiles: ["ingest-data", "website"]

  #start up the local build
  localbuild:
    container_name: localbuild
    build:
      context: .
      dockerfile: Dockerfile-client  
    restart: on-failure:10
    depends_on: 
      - tornado
    networks:
      - some-net 
    ports:
      - "5000:5000"
    profiles: ["ingest-data", "website"]
             

networks:
  some-net:
    driver: bridge
      
